import "./styles/main.css";
import "../src/DOMs.js";
import { cityData, enterKey, submit, extraInfoimg } from "../src/current";
import { forecastData } from "../src/forecast";
import { favData } from "../src/fav";
import { switch1 } from "../src/DOMs.js";

enterKey();
submit();
extraInfoimg();
cityData("Mugla");
forecastData("Mugla");
favData("istanbul");
favData("Rome");
favData("Berlin");
favData("Paris");
favData("Madrid");
favData("London");

switch1.addEventListener("click", function () {
  if (switch1.checked) {
    tempc.classList.toggle("hide");
    tempf.classList.toggle("hide");
    infoApi0.classList.toggle("hide");
    infoApi1.classList.toggle("hide");
    infoApi3.classList.toggle("hide");
    infoApi33.classList.toggle("hide");
    infoTitle1c.classList.toggle("hide");
    infoTitle1f.classList.toggle("hide");
    infoTitle2c.classList.toggle("hide");
    infoTitle2f.classList.toggle("hide");
    infoTitle3c.classList.toggle("hide");
    infoTitle3f.classList.toggle("hide");
    Parisc.classList.toggle("hide");
    Parisf.classList.toggle("hide");
    Romec.classList.toggle("hide");
    Romef.classList.toggle("hide");
    istanbulc.classList.toggle("hide");
    istanbulf.classList.toggle("hide");
    Londonc.classList.toggle("hide");
    Londonf.classList.toggle("hide");
    Madridc.classList.toggle("hide");
    Madridf.classList.toggle("hide");
    Berlinc.classList.toggle("hide");
    Berlinf.classList.toggle("hide");
  } else {
    tempc.classList.toggle("hide");
    tempf.classList.toggle("hide");
    infoApi0.classList.toggle("hide");
    infoApi1.classList.toggle("hide");
    infoApi3.classList.toggle("hide");
    infoApi33.classList.toggle("hide");
    infoTitle1c.classList.toggle("hide");
    infoTitle1f.classList.toggle("hide");
    infoTitle2c.classList.toggle("hide");
    infoTitle2f.classList.toggle("hide");
    infoTitle3c.classList.toggle("hide");
    infoTitle3f.classList.toggle("hide");
    Parisc.classList.toggle("hide");
    Parisf.classList.toggle("hide");
    Romec.classList.toggle("hide");
    Romef.classList.toggle("hide");
    istanbulc.classList.toggle("hide");
    istanbulf.classList.toggle("hide");
    Londonc.classList.toggle("hide");
    Londonf.classList.toggle("hide");
    Madridc.classList.toggle("hide");
    Madridf.classList.toggle("hide");
    Berlinc.classList.toggle("hide");
    Berlinf.classList.toggle("hide");
  }
});
